# -*- coding: utf-8 -*-
"""3laba

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z3HWZ83JxOAN7HL-zM1pxozkCQ-uibYg
"""

#1
num = int(input())
if num == 1:
  print('Январь')
elif num == 2:
  print('Февраль')
elif num == 3:
  print('Март')
elif num == 4:
  print('Апрель')
elif num == 5:
  print('Май')
elif num == 6:
  print('Июнь')
elif num == 7:
  print('Июль')
elif num == 8:
  print('Август')
elif num == 9:
  print('Сентябрь')
elif num == 10:
  print('Октябрь')
elif num == 11:
  print('Ноябрь')
elif num == 12:
  print('Декабрь')
else:
  print("Введите число от 1 до 12!")

#2
print('Введите циферку')
num = int(input())
if num % 2 == 0:
  print('Четное')
elif num % 2 != 0:
  print('Нечетное')

#3
N = int(input())
if N > 40:
  print('stonks')
elif N < 40:
  print('not stonks')

#4
def is_year_leap(year):
    return year % 400 == 0 or (year % 4 == 0 and year % 100 != 0)

n = int(input())
if is_year_leap(n):
    print('True')
else:
    print('False')

#5
def is_prime(n):
  if n <= 1:
      return False
  if n == 2:
      return True
  if n % 2 == 0:
      return False

  i = 3
  while i * i <= n:
      if n % i == 0:
          return False
      i += 2

  return True

n = int(input())
if is_prime(n):
    print('True')
else:
    print('False')

#6
def swapik(a, b):
  a1 = abs(-138 / 2) ** 1.3
  a2 = abs((-69 / (28 ** 5.1)) * 4)
  c1 = (a > b * 3.6)
  c2 = (a1 <= b <= a2)

  if c1 or c2:
        return b, a
  else:
        return a, b
try:
    a = float(input())
    b = float(input())

    a_new, b_new = swapik(a, b)

    print(a_new)
    print(b_new)

except ValueError:
    print("Введите числовые значения")

#7
def orig():
    nums = []
    for i in range(5):
        while True:
            try:
                nums.append(int(input()))
                break
            except ValueError:
                pass

    u = len(nums) == len(set(nums))
    c_e = 0
    c_n = 0
    c_r = 0
    c_odd = 0

    for n in nums:
        if n % 2 == 0:
            c_e += 1
        else:
            c_odd += 1
        if n < 0:
            c_n += 1
        if -256 <= n <= 1024:
            c_r += 1

    if u:
        print(f"Числа2 уникальные.")
    else:
        print(f"Числа не уникальные.")

    print(f"Количество четных чисел: {c_e}")
    print(f"Количество нечетных чисел: {c_odd}")
    print(f"Количество отрицательных чисел: {c_n}")
    print(f"Количество чисел в промежутке [-256 ; 1024]: {c_r}")

orig()

#Задание повышенной сложности
def zxc():

    while True:
        try:
            a = float(input())
            b = float(input())
            c = float(input())

            if c + 3 == 0:
                print("На ноль нельзя делить.")
                continue

            break
        except ValueError:
            pass

    rez = (a**2 + b**3) / (c + 3) / 4

    print(rez)

    int_rez = int(rez)

    if abs(rez - int_rez) > 1e-9:
        print("Не целое число.")
        return

    if int_rez % 2 == 0:
        print("четное")
    else:
        print("нечетное")

zxc()