# -*- coding: utf-8 -*-
"""6 laba

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X6MDD2gsVOMDQoFsJXXoxHXVBf-kKXe-
"""

#1
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression

fahrenheit = [[32.0], [100.0], [212.0], [-40.0], [0.0]]
kelvin = [[273.15], [310.93], [373.15], [233.15], [255.37]]

plt.figure(figsize=(10, 5))
plt.scatter(fahrenheit, kelvin, label='исходные данные', color='orange')
plt.xlabel('Fahrenheit')
plt.ylabel('Kelvin')
plt.legend()
plt.grid(True)
plt.show()

lr = LinearRegression()
lr.fit(fahrenheit, kelvin)

f_test = [[50], [75], [120]]
k_pred = lr.predict(f_test)

for f, k in zip(f_test, k_pred):
    print(f'Фаренгейт {f} = Кельвин {k}')

#2
!git clone https://github.com/514354/Dabakov_PI311

#3
categories = ['A', 'B', 'C', 'D']
values = [10, 25, 15, 30]

#1)cтолбчатая диаграмма
plt.figure(figsize=(5,3))
plt.bar(categories, values, color='skyblue')
plt.title("Столбчатая диаграмма")
plt.show()

#2)круговая диаграмма
plt.figure(figsize=(5,3))
plt.pie(values, labels=categories, autopct='%1.1f%%')
plt.title("Круговая диаграмма")
plt.show()

#3)гистограмма
data = np.random.randn(1000)
plt.figure(figsize=(5,3))
plt.hist(data, bins=30, color='green', alpha=0.7)
plt.title("Гистограмма")
plt.show()

#4
import math

print(f"Число Эйлера: {math.e}") #
print(f"Число Пи: {math.pi}")    #
print(f"nan: {math.nan}")        #

n = 5
pamiat = 128

fact = math.factorial(n)
print(f"Факториал числа {n}: {fact}") #

gcd_val = math.gcd(n, pamiat)
print(f"Наибольший общий делитель для {n} и {pamiat}: {gcd_val}")

#Заданиe повышенной сложности №1
plt.figure(figsize=(5,5))

head_x = [2, 8, 8, 2, 2]
head_y = [2, 2, 8, 8, 2]
plt.plot(head_x, head_y, color='black')

plt.plot([2, 3, 4], [8, 10, 8], color='black') # Левое
plt.plot([6, 7, 8], [8, 10, 8], color='black') # Правое

plt.scatter([3.5, 6.5], [6, 6], color='brown', s=100)

plt.scatter([5], [4.5], color='red', marker='v')
plt.plot([4.5, 5, 5.5], [3.5, 4, 3.5], color='black')

plt.xlim(0, 10)
plt.ylim(0, 11)
plt.title("котейка")
plt.show()

#Задание повышенной сложности №2
import tensorflow as tf

# Загрузка данных
mnist = tf.keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

# Названия классов [cite: 45]
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

# Показать один элемент [cite: 47]
plt.figure()
plt.imshow(train_images[0], cmap='gray')
plt.title(f"Тип: {class_names[train_labels[0]]}")
plt.show()

#Matplotlib - создание графиков и визуализация
#Numpy - работа с массивами и математика
#Tensorflow/Keras - создание и тренировка нейросетей# fix

#123
