# -*- coding: utf-8 -*-
"""Лаба 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jdvUGWZGMrtD_N0Qb3QyJqvDtQ7rvi4F
"""

#1
a = 5
b = int(input())
c = a*b
print(c)

#2
a = int(input())
b = int(input())
print((a + b) ** 2)

#3
a = 15
b = 10
c = int(input())
print((a + b)/c)

#4
a = int(input())
b = int(input())
print(a**2 + 2*a*b + b**2)

#5
a = int(input())
b = int(input())
c = int(input())
P = a + b + c
p = P/2
S = ((p*(p-a)*(p-b)*(p-c))**0.5)
if a != b and b!= c and a != c:
  print('Площадь =', S, 'Периметр =', P)
else:
  print('Треугольник должен быть неравнобедренным')

#6
a = int(input())
b = int(input())
c = ((a**3 + 14)/5) * b
print(c)

#7
a = int(input())
n = int(input())
print(a**2//n)

#8
a = float(input())
b = float(input())
c = int(input())
d = int(input())
print(a//b, c * d, c % d)

#повышенная сложность №1
print('Введите число секунд')
n = int(input())
print(n/60, 'минут', n/60/60, 'часов', n/60/60/24, 'дней')

#повышенная сложность №2
n = int(input())
nn = str(n) + str(n)
nnn = str(n) + str(n) + str(n)
print(n + int(nn) + int(nnn))